import type { Metadata } from "next";
// LAYOUTS
import Container_App from "@/app/[locale]/components/layouts/containers/ContainerApp";
// STYLES
import "@/app/[locale]/utils/constants/styles/globals.css"

export const metadata: Metadata = {
  title: "Restaurant -j The Kitchen",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <body>
        <Container_App>{children}</Container_App>
      </body>
    </html>
  );
}
