import type { Metadata } from "next";
// STYLES

export const metadata: Metadata = {
  title: "Restaurant -j The Kitchen",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <body>
        {children}
      </body>
    </html>
  );
}
